global:
  # Default interval for scraping metrics from targets
  scrape_interval: 10s

scrape_configs:
  # Define a job to scrape metrics from the FastAPI app
  - job_name: 'fastapi-app'
    static_configs:
      # Targets list: Prometheus will scrape metrics from this service
      # Here, "api" is the service name in Docker Compose (container running FastAPI)
      # and "8000" is the exposed port where the app runs
      - targets: ['api:8000']
