services:
  - type: web
    name: fastapi-car-price-api   # Name of your service on Render
    env: docker                   # Since you are using Dockerfile
    plan: free                    # Free plan
    branch: main                  # Repo branch to deploy from
    autoDeploy: true              # Auto-deploy on git push
    dockerfilePath: ./Dockerfile  # Path to Dockerfile (correct if it's in project root)
    envVars:
      - key: MODEL_PATH
        value: app/models/model.joblib
