services:
  # ----------------------------
  # FastAPI Car Price API Service
  # ----------------------------
  - type: web
    name: fastapi-car-price-api        # Name of the service on Render
    env: docker                        # Use Docker for deployment
    plan: free                         # Render free plan (limited resources)
    branch: main                       # Deploy from the "main" branch
    autoDeploy: true                   # Automatically deploy new commits to main
    dockerfilePath: ./Dockerfile       # Path to Dockerfile for building the app

    envVars:
      - key: MODEL_PATH                # Environment variable for ML model location
        value: app/models/model.joblib # Path inside container to the trained model
